"""
SatQuery AI — Phase 11 Grounding End-to-End Test
Verifies QUERY + IMAGE -> GROUNDING MODEL -> BOXES / REGIONS -> EVIDENCE OVERLAY
"""

import requests
import json
import time

base_url = 'http://localhost:8000'

# 1. Upload Cartosat GeoTIFF
tif_path = 'c:/Users/hasin/OneDrive/Desktop/sat1/SatQueryAI/tests/sample_cartosat_utm43n.tif'
with open(tif_path, 'rb') as f:
    up = requests.post(f'{base_url}/api/upload', data=f.read(), headers={'X-File-Name': 'sample_cartosat_utm43n.tif'}).json()

file_id = up['fileId']
print(f"[1. UPLOADED RASTER]: file_id = {file_id}")

# 2. Grounding Query
grounding_query = "Find buildings near the center."
an_req = {
    "file_id": file_id,
    "analysis_id": "analysis_grounding_center_buildings",
    "query": grounding_query,
    "configuration": {"model_type": "DOMAIN-ADAPTED"}
}
an_resp = requests.post(f'{base_url}/api/analyze', json=an_req).json()

print(f"\n[2. GROUNDING ANALYSIS RESPONSE]:")
print(f"  Detected Task: {an_resp.get('detectedTask')}")
print(f"  Selected Model: {an_resp.get('selectedModel', {}).get('name')}")
print(f"  Text Answer:\n    {an_resp.get('textAnswer')}")
print(f"  Key Findings:")
for kf in an_resp.get('keyFindings', []):
    print(f"    * {kf}")

print(f"\n[3. GROUNDING BOXES / REGIONS]:")
boxes = an_resp.get('groundingBoxes', [])
print(f"  Total Boxes Generated: {len(boxes)}")
for b in boxes:
    print(f"    - ID: {b['id']} | Label: {b['label']}")
    print(f"      Coordinates (ymin%, xmin%, ymax%, xmax%): {b['box']}")
    print(f"      Calibrated Confidence: {b['confidence']}")
    if 'geo_coordinates' in b:
        print(f"      Physical GeoBounds: {b['geo_coordinates']['bounds']}")

# 4. Evidence Overlay Endpoint
ev_resp = requests.get(f"{base_url}/api/evidence/analysis_grounding_center_buildings").json()
print(f"\n[4. EVIDENCE OVERLAY ENDPOINT (/api/evidence/analysis_grounding_center_buildings)]:")
print(f"  Evidence Count: {ev_resp.get('count')}")
print(f"  Grounding Boxes: {len(ev_resp.get('groundingBoxes', []))}")

# 5. Verification Assertions
assert an_resp.get('detectedTask') == 'Text-Guided Region Grounding', "Task must be Text-Guided Region Grounding"
assert len(boxes) > 0, "Must return at least 1 actual grounding box"
for b in boxes:
    assert b['label'] != 'TECH PARK', "Must NOT be hardcoded TECH PARK"
    assert b['confidence'] != 0.91, "Must NOT be hardcoded 0.91"
    assert len(b['box']) == 4, "Must have valid 4-coordinate bounding box"

print("\n" + "=" * 60)
print("PHASE 11 GROUNDING VERIFICATION PASSED SUCCESSFULLY!")
print("Actual coordinates/boxes generated by Grounding Specialist.")
print("Zero hardcoded 'TECH PARK CONF 0.91' data.")
print("=" * 60)
